### ISSUE TITLE
I checked the latest changes with StatList, I have bad news

### ISSUE THREAD

**Issue by Araksson** [ThePhrozenKeep/D2MOO#27]
The errors remain exactly the same.

This was added that LoadItemStatCost does not read the OPs 0/8/9/10/11 that correspond to the same OPs that fail with the STATLIST_UpdateUnitNewStat function and STATLIST_InsertStatModOrFail

(As a side note, LoadISC from the pre-bulk changes version worked fine (it's the one I'm using))

Sorry for my slowness, I still haven't finished rearranging all my code, it's very long and I didn't check even half of the D2Moo functions (corresponding to ItemsFunctions, DRLG, Path and Missiles).
The good news is that I have made several fixes to the Path and Skills functions to make them work much better (and in some cases, to work directly).

And with Statlist I can't fix those errors.

I also don't have enough time to repair all the maximum details, but I would like to get it since it is very useful to handle all the statlists to try to expand them a bit with some custom code (in addition to expanding the ISC OPs which are also very useful)

**Comment by Lectem** [comment]
It seems the issue is related to `0x6FDB64A0` (what you call `STATLIST_UpdateUnitNewStat`).

The other functions look fine to me
Using an amulet with both `STATLIST_InsertStatModOrFail` and `LoadItemStatCost`:
![image](https://user-images.githubusercontent.com/6024225/117583509-c866cd80-b107-11eb-8f5a-e47a8f1a786c.png)
On a character with base stats:
![image](https://user-images.githubusercontent.com/6024225/117583516-d0bf0880-b107-11eb-85fb-4c1ee7fadbf6.png)
Yields 
![image](https://user-images.githubusercontent.com/6024225/117583521-d61c5300-b107-11eb-803e-597737a4964d.png)

However when using `STATLIST_UpdateUnitNewStat` it indeed give me something wrong (without even using the amulet!)
![image](https://user-images.githubusercontent.com/6024225/117583552-006e1080-b108-11eb-839b-329ed2796d2d.png)

I'll investigate.

**Comment by Lectem** [comment]
I think #28 fixed this, feel free to reopen if issues remain.
